# Generated by Django 4.0.4 on 2022-06-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_champion_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='damage',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=0),
        ),
    ]
