# Generated by Django 4.0.4 on 2022-06-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_champion_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='champ_type',
            field=models.CharField(choices=[('Controller', 'Controller'), ('Fighter', 'Fighter'), ('Mage', 'Mage'), ('Marksman', 'Marksman'), ('Slayer', 'Slayer'), ('Tank', 'Tank'), ('Noob', 'Noob')], default='Noob', max_length=20),
        ),
    ]
