# Generated by Django 4.0.4 on 2022-06-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_champion_champ_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='toughness',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='utlity',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=0),
        ),
    ]
